#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : su-exec
Version  : 0.2
Release  : 1
URL      : https://github.com/ncopa/su-exec/archive/v0.2.tar.gz
Source0  : https://github.com/ncopa/su-exec/archive/v0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: su-exec-bin = %{version}-%{release}
Requires: su-exec-license = %{version}-%{release}

%description
# su-exec
switch user and group id, setgroups and exec
This is a simple tool that will simply execute a program with different
privileges. The program will not run as a child, like su and sudo, so we
work around TTY and signal issues.

%package bin
Summary: bin components for the su-exec package.
Group: Binaries
Requires: su-exec-license = %{version}-%{release}

%description bin
bin components for the su-exec package.


%package license
Summary: license components for the su-exec package.
Group: Default

%description license
license components for the su-exec package.


%prep
%setup -q -n su-exec-0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562824869
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1562824869
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/su-exec
cp LICENSE %{buildroot}/usr/share/package-licenses/su-exec/LICENSE
install -p -D -m 0755 su-exec %{buildroot}/usr/bin/su-exec

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/su-exec

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/su-exec/LICENSE
